/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabRouteImport } from './routes/lab'
import { Route as HubRouteImport } from './routes/hub'
import { Route as GrillingRouteImport } from './routes/grilling'
import { Route as EvaluatorRouteImport } from './routes/evaluator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AffairsRouteImport } from './routes/affairs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubIndexRouteImport } from './routes/hub.index'
import { Route as ArchiveSlugRouteImport } from './routes/archive.$slug'
import { Route as ApiGrillingRouteImport } from './routes/api/grilling'
import { Route as ApiEvaluateRouteImport } from './routes/api/evaluate'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const GrillingRoute = GrillingRouteImport.update({
  id: '/grilling',
  path: '/grilling',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluatorRoute = EvaluatorRouteImport.update({
  id: '/evaluator',
  path: '/evaluator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AffairsRoute = AffairsRouteImport.update({
  id: '/affairs',
  path: '/affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubRoute,
} as any)
const ArchiveSlugRoute = ArchiveSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArchiveRoute,
} as any)
const ApiGrillingRoute = ApiGrillingRouteImport.update({
  id: '/api/grilling',
  path: '/api/grilling',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluateRoute = ApiEvaluateRouteImport.update({
  id: '/api/evaluate',
  path: '/api/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affairs': typeof AffairsRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/evaluator': typeof EvaluatorRoute
  '/grilling': typeof GrillingRoute
  '/hub': typeof HubRouteWithChildren
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/grilling': typeof ApiGrillingRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/hub/': typeof HubIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affairs': typeof AffairsRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/evaluator': typeof EvaluatorRoute
  '/grilling': typeof GrillingRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/grilling': typeof ApiGrillingRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/hub': typeof HubIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affairs': typeof AffairsRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/evaluator': typeof EvaluatorRoute
  '/grilling': typeof GrillingRoute
  '/hub': typeof HubRouteWithChildren
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/grilling': typeof ApiGrillingRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/hub/': typeof HubIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affairs'
    | '/archive'
    | '/dashboard'
    | '/evaluator'
    | '/grilling'
    | '/hub'
    | '/lab'
    | '/login'
    | '/quiz'
    | '/signup'
    | '/api/evaluate'
    | '/api/grilling'
    | '/archive/$slug'
    | '/hub/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affairs'
    | '/archive'
    | '/dashboard'
    | '/evaluator'
    | '/grilling'
    | '/lab'
    | '/login'
    | '/quiz'
    | '/signup'
    | '/api/evaluate'
    | '/api/grilling'
    | '/archive/$slug'
    | '/hub'
  id:
    | '__root__'
    | '/'
    | '/affairs'
    | '/archive'
    | '/dashboard'
    | '/evaluator'
    | '/grilling'
    | '/hub'
    | '/lab'
    | '/login'
    | '/quiz'
    | '/signup'
    | '/api/evaluate'
    | '/api/grilling'
    | '/archive/$slug'
    | '/hub/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffairsRoute: typeof AffairsRoute
  ArchiveRoute: typeof ArchiveRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EvaluatorRoute: typeof EvaluatorRoute
  GrillingRoute: typeof GrillingRoute
  HubRoute: typeof HubRouteWithChildren
  LabRoute: typeof LabRoute
  LoginRoute: typeof LoginRoute
  QuizRoute: typeof QuizRoute
  SignupRoute: typeof SignupRoute
  ApiEvaluateRoute: typeof ApiEvaluateRoute
  ApiGrillingRoute: typeof ApiGrillingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grilling': {
      id: '/grilling'
      path: '/grilling'
      fullPath: '/grilling'
      preLoaderRoute: typeof GrillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluator': {
      id: '/evaluator'
      path: '/evaluator'
      fullPath: '/evaluator'
      preLoaderRoute: typeof EvaluatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affairs': {
      id: '/affairs'
      path: '/affairs'
      fullPath: '/affairs'
      preLoaderRoute: typeof AffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/archive/$slug': {
      id: '/archive/$slug'
      path: '/$slug'
      fullPath: '/archive/$slug'
      preLoaderRoute: typeof ArchiveSlugRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/api/grilling': {
      id: '/api/grilling'
      path: '/api/grilling'
      fullPath: '/api/grilling'
      preLoaderRoute: typeof ApiGrillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluate': {
      id: '/api/evaluate'
      path: '/api/evaluate'
      fullPath: '/api/evaluate'
      preLoaderRoute: typeof ApiEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArchiveRouteChildren {
  ArchiveSlugRoute: typeof ArchiveSlugRoute
}

const ArchiveRouteChildren: ArchiveRouteChildren = {
  ArchiveSlugRoute: ArchiveSlugRoute,
}

const ArchiveRouteWithChildren =
  ArchiveRoute._addFileChildren(ArchiveRouteChildren)

interface HubRouteChildren {
  HubIndexRoute: typeof HubIndexRoute
}

const HubRouteChildren: HubRouteChildren = {
  HubIndexRoute: HubIndexRoute,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffairsRoute: AffairsRoute,
  ArchiveRoute: ArchiveRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EvaluatorRoute: EvaluatorRoute,
  GrillingRoute: GrillingRoute,
  HubRoute: HubRouteWithChildren,
  LabRoute: LabRoute,
  LoginRoute: LoginRoute,
  QuizRoute: QuizRoute,
  SignupRoute: SignupRoute,
  ApiEvaluateRoute: ApiEvaluateRoute,
  ApiGrillingRoute: ApiGrillingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
